# Generated for Qurilish Market MVP

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Category', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=120, verbose_name='Название')), ('slug', models.SlugField(max_length=140, unique=True, verbose_name='Slug')), ('description', models.TextField(blank=True, verbose_name='Описание')), ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'))], options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории', 'ordering': ['name']}),
        migrations.CreateModel(name='Seller', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=160, verbose_name='Название продавца')), ('phone', models.CharField(max_length=40, verbose_name='Телефон')), ('city', models.CharField(max_length=80, verbose_name='Город')), ('address', models.CharField(blank=True, max_length=255, verbose_name='Адрес')), ('is_active', models.BooleanField(default=True, verbose_name='Активен'))], options={'verbose_name': 'Продавец', 'verbose_name_plural': 'Продавцы', 'ordering': ['name']}),
        migrations.CreateModel(name='Product', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('name', models.CharField(max_length=180, verbose_name='Название')), ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')), ('description', models.TextField(verbose_name='Описание')), ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')), ('unit', models.CharField(default='шт', max_length=30, verbose_name='Единица')), ('stock', models.PositiveIntegerField(default=0, verbose_name='Остаток')), ('city', models.CharField(max_length=80, verbose_name='Город')), ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Фото')), ('is_active', models.BooleanField(default=True, verbose_name='Активен')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')), ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.category', verbose_name='Категория')), ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.seller', verbose_name='Продавец'))], options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары', 'ordering': ['-created_at']}),
        migrations.CreateModel(name='Order', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('customer_name', models.CharField(max_length=120, verbose_name='Имя клиента')), ('phone', models.CharField(max_length=40, verbose_name='Телефон')), ('city', models.CharField(blank=True, max_length=80, verbose_name='Город')), ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')), ('comment', models.TextField(blank=True, verbose_name='Комментарий')), ('status', models.CharField(choices=[('new', 'Новая'), ('processing', 'В обработке'), ('confirmed', 'Подтверждена'), ('cancelled', 'Отменена'), ('completed', 'Выполнена')], default='new', max_length=20, verbose_name='Статус')), ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')), ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='marketplace.product', verbose_name='Товар'))], options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки', 'ordering': ['-created_at']}),
        migrations.AddIndex(model_name='product', index=models.Index(fields=['slug'], name='marketplace_slug_d409f0_idx')),
        migrations.AddIndex(model_name='product', index=models.Index(fields=['city'], name='marketplace_city_0d3459_idx')),
        migrations.AddIndex(model_name='product', index=models.Index(fields=['is_active'], name='marketplace_is_acti_90c2f9_idx')),
    ]
